# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - StudentPerformanceCheck

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerwiem.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_877e579e553c4c1e924b5fbdfd1f6f2e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8b56109da7cc467d9485ad4e1bc8cdbe }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerwiem.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_877e579e553c4c1e924b5fbdfd1f6f2e }}/studentperformance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'StudentPerformanceCheck'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_162b17eb9ccd42ebbcd9b7b3fdf66374 }}
        images: 'testdockerwiem.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_877e579e553c4c1e924b5fbdfd1f6f2e }}/studentperformance:${{ github.sha }}'