# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentcheckperformance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerwiem.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4ec4c1e73cb3489a8feb5a547d23cbca }}
        password: ${{ secrets.AzureAppService_ContainerPassword_19be2d556bd645268262ee46cc5f1b03 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerwiem.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4ec4c1e73cb3489a8feb5a547d23cbca }}/testdockerwiem/studentperformance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentcheckperformance'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6f9e62d6f7b049ceac72e9a0f5437224 }}
        images: 'testdockerwiem.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4ec4c1e73cb3489a8feb5a547d23cbca }}/testdockerwiem/studentperformance:${{ github.sha }}'