# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentcheckperformance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerwiem.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e6e8082e1e274299927d46734aead56b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_84e8266b5e544bbc9a95d77c5ef2d7f6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerwiem.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e6e8082e1e274299927d46734aead56b }}/studentperformance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentcheckperformance'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cf45e1c0660b430fba441c90a4c249da }}
        images: 'testdockerwiem.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e6e8082e1e274299927d46734aead56b }}/studentperformance:${{ github.sha }}'